### ISSUE TITLE
開啟網頁後不會自動簽到問題

### ISSUE THREAD

**Issue by pearwb1235** [oddstab/genshin-impact-auto-sign#1]
![image](https://user-images.githubusercontent.com/46672356/193485544-3a7c02be-4165-406b-8ce7-02d0c9ca77cc.png)

由於官方網頁改版
雖然content_scripts作用的網址已更改
但尋找element(網頁元素)的程式有問題
以下提供一些想法

---

https://github.com/oddstab/genshin-impact-auto-sign/blob/bf8f063750c955f32473700c7519571424d4fd20/src/content.ts#L8
如果依照原作者設計 先尋找所有簽到格子
應該改成如下
`document.querySelectorAll("div[class*=components-home-assets-__sign-content_---sign-list---] > div");`

---

https://github.com/oddstab/genshin-impact-auto-sign/blob/bf8f063750c955f32473700c7519571424d4fd20/src/content.ts#L38
同時現在簽到格子父元素 不再有active字眼(現在是在子元素)
可以解決的方式(其實方法有很多# 舉兩個)
1. 更改外層的判斷方式
`contents.find((el) => el.className.includes("sign-wrapper"));`
2. 搜尋裡面的 actived-day 字眼(右上角紅點的父元素)
`contents.find((el) => el.querySelector(":scope > [class*=actived-day]"));`
// :scope 意思是指 el 這個元素  也可以去掉前面的 `:scope >`

---

https://github.com/oddstab/genshin-impact-auto-sign/blob/bf8f063750c955f32473700c7519571424d4fd20/src/content.ts#L20
最後 loadMoreSignContent 這個方法找到元素也是被改了
但因為簽到會自動換排(例如第9天 第一個格子是簽過的第8天)
其實也沒有必要找所有格子

---

最後提供一行暴力解(x
`document.querySelector("[class*=components-home-assets-__sign-content_---sign-wrapper]")?.click()`

**Comment by oddstab** [comment]
@pearwb1235 謝謝建議~ 我會參考納入
最近已經把自動簽到改好了，但還在測試補簽 可能還需要一會兒
