### ISSUE TITLE
簽到語言問題

### ISSUE THREAD

**Issue by pearwb1235** [oddstab/genshin-impact-auto-sign#2]
正如巴友所說自動簽到後的獎勵寄信內容是英文的
https://forum.gamer.com.tw/Co.php?bsn=36730&sn=198154&subbsn=20&bPage=0

參考解決方式

簽到方法
https://github.com/oddstab/genshin-impact-auto-sign/blob/f6ef61a0b6e055c6c12d0a31da33ad3cac16fd5e/src/SignHelper.ts#L131-L134

可以在POST的時候在 body 攜帶 lang 欄位
`let res = await this.send(this.signPath, "POST", { act_id: "e202102251931481", lang: "zh-tw" });`

如果要根據使用者語言 網站的語言設定是放在cookie的`mi18nLang`
不過這方面可能要告知用戶 會蒐集cookie之類的 比較麻煩

以上
感謝大大 這幾天簽到很順利:3

**Comment by oddstab** [comment]
@pearwb1235 變英文我知道，但想說能簽到就好，暫時沒改XD

**Comment by oddstab** [comment]
已修正成根據瀏覽器語言來簽到
